export const theme = {
  colors: {
    // Warm, soft palette inspired by cozy self-care companion apps —
    // muted sage/peach rather than saturated primary colors.
    primary: '#5FB89C',
    primaryDark: '#3F9A80',
    secondary: '#FFB199',
    background: '#FBF6EE',
    card: '#FFFFFF',
    cardAlt: '#FFF8EF',
    text: '#3D3229',
    subtext: '#8A7F72',
    gray: '#ABA096',
    lightGray: '#F3ECE1',
    border: '#EFE6D8',
    success: '#5FB89C',
    warning: '#FFC168',
    error: '#F0787E',
    happiness: '#FFB55E',
    hunger: '#F0898F',
    energy: '#6FB8DE',
    health: '#7ED6A7',
  },
  fonts: {
    regular: 'Nunito-Regular',
    semiBold: 'Nunito-SemiBold',
    bold: 'Nunito-Bold',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 10,
    md: 20,
    lg: 26,
    xl: 32,
    full: 9999,
  },
  shadows: {
    small: {
      shadowColor: '#4A3B2A',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 2,
    },
    medium: {
      shadowColor: '#4A3B2A',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.09,
      shadowRadius: 16,
      elevation: 5,
    },
  },
};
