export const theme = {
  colors: {
    primary: '#4ECDC4',
    secondary: '#FFD166',
    background: '#FCFCFC',
    card: '#FFFFFF',
    text: '#2A2A2A',
    subtext: '#757575',
    gray: '#9E9E9E',
    lightGray: '#F5F5F5',
    success: '#06D6A0',
    warning: '#FFD166',
    error: '#EF476F',
    happiness: '#FF9F1C',
    hunger: '#E63946',
    energy: '#118AB2',
    health: '#06D6A0',
  },
  fonts: {
    regular: 'Nunito-Regular',
    semiBold: 'Nunito-SemiBold',
    bold: 'Nunito-Bold',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    full: 9999,
  },
  shadows: {
    small: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    medium: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 4,
    },
  },
};